# Generated by Django 5.2 on 2025-08-01 11:37

from django.db import migrations
from django.contrib.auth.models import User


def create_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('store', 'UserProfile')
    User = apps.get_model('auth', 'User')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def reverse_create_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('store', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_create_user_profiles),
    ]
